# Generated by Django 3.2.25 on 2024-12-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_tag_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='tags',
            field=models.ManyToManyField(to='core.Tags'),
        ),
    ]
