# Generated by Django 3.2.25 on 2025-01-02 09:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20241231_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.receipe_image_file_path),
        ),
    ]
